### ISSUE TITLE
Could not run the app - intro-example outdated?

### ISSUE THREAD

**Issue by antonioaguilar** [nx-js/intro-example#2]
I was trying to run this app but it doesn't seem to run. The README.md says the demo runs on port 3000 but the express server actually runs on port 3001. After correcting that, the app throws the following error on the browser console: 

```
bundle.js:439 Uncaught (in promise) Error: duplicate middlewares: render
    at validateMiddlewares (http://localhost:3000/bundle.js:439:12)
    at setupNodeAndChildren (http://localhost:3000/bundle.js:538:6)
    at onNodeAdded (http://localhost:3000/bundle.js:515:6)
    at processAddedNode (http://localhost:3000/bundle.js:344:4)
    at Set.forEach (native)
    at processAddedNodes (http://localhost:3000/bundle.js:333:15)
```

**Comment by solkimicreb** [comment]
Yes, I forgot to update it after the last update. The `app` component includes the `render` middleware from now on by default. So this code

```js
nx.components.app()
  .use(nx.middlewares.render({
    template: require('./view.html'),
    style: require('./style.css')
  }))
  .register('intro-app')
```

has to be replaced with this

```js
nx.components.app({
    template: require('./view.html'),
    style: require('./style.css')
 })
 .register('intro-app')
```

Otherwise it throws an error for duplicate `render` middlewares (one from the app and one from us - added explicitly).

I will fix it today and if I have time I will also add some test.
Thx for the issue @antonioaguilar !

**Comment by solkimicreb** [comment]
I fixed it, thanks again. Closing this issue now.
